services:
  backend:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - /app/__pycache__

  frontend:
    volumes:
      - ./my-next-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
