version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: arsa
      POSTGRES_PASSWORD: arsa1984@
      POSTGRES_DB: chetchat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
